### ISSUE TITLE
Bas-relief addon error

### ISSUE THREAD

**Issue by stefyson** [vilemduha/blendercam#108]
Hello,
I have an issue regarding bas-relief addon; When i press the Calculate relief button I got this error: 

Traceback (most recent call last):
  File "D:\Apps\blender\blender-2.76-windows64\blender-2.76-windows64\2.76\scripts\addons\basrelief.py", line 946, in execute
    relief(br)
  File "D:\Apps\blender\blender-2.76-windows64\blender-2.76-windows64\2.76\scripts\addons\basrelief.py", line 717, in relief
    tonemap(nar)
  File "D:\Apps\blender\blender-2.76-windows64\blender-2.76-windows64\2.76\scripts\addons\basrelief.py", line 601, in tonemap
    maxheight=i.max()
  File "D:\Apps\blender\blender-2.76-windows64\blender-2.76-windows64\2.76\python\lib\site-packages\numpy\core\_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity

location: unknown location:-1

Is from my setup or is really an issue?

**Comment by vilemduha** [comment]
Hi, what resolution is your input image? input images should be multiples of powers of two.
Like image with a ratio of 3:2 i'd make 3*512 = 1536  and 2*512 = 1024, so input image would be an .exr file with resolution 1536x1024.
Is that understandable? if the error persists also with this kind of input, let us know.
