### ISSUE TITLE
Install Problem on MacOS

### ISSUE THREAD

**Issue by rsaccon** [vilemduha/blendercam#219]
I am on an Intel MacOS 11.6.6 and Blender 3.1.2

I tried to install the dependencies, git cloned the addon and linked to it from the blender addon directory. When I tried to enable blendercam this is what I got:
```
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.1/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/robertosaccon/Library/Application Support/Blender/3.1/scripts/addons/blendercam/__init__.py", line 1321, in <module>
    ui.CAM_UL_operations,
NameError: name 'ui' is not defined
```

then I checked all installed python modules (from within the blender Python Console):
```
>>> pip.main(['list'])
Package            Version
------------------ ---------
certifi            2021.10.8
charset-normalizer 2.0.10
Cython             0.29.26
Equation           1.2.1
grpcio             1.44.0
idna               3.3
numpy              1.22.0
package-name       0.1
pip                22.1
protobuf           3.20.1
py-slvs            1.0.4
requests           2.27.1
setuptools         58.1.0
Shapely            1.8.2
six                1.16.0
toxicblend         0.2.0
urllib3            1.26.8
wheel              0.37.1
zstandard          0.16.0
0
```
It looks like `vtk` is missing. And I think I saw `vtk` mentioned somewhere in the blendercam docs.

I tried to install it again and this is what I got:
```
>>> pip.main(['install', 'vtk'])
1

WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
ERROR: Could not find a version that satisfies the requirement vtk (from versions: none)
ERROR: No matching distribution found for vtk
```

So do I have a pip problem with vtk ? Or am I just missing something ?

btw. I could install vtk via brew without any problems:
```
brew info vtk   
vtk: stable 9.1.0 (bottled), HEAD
```

Anybody knows hot to get blendercam installed on a Mac ?

**Comment by vernoceedee** [comment]
Sorry, I don't have an answer but here because I also have issues, trying to use this on MacOS.  Did you ever get this to work?

I'm on Apple Silicon Mac and having downloaded the source for blenderCam and set the file path to the scripts, it shows in the add-ons but when trying to enable, I get this:
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.3/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/Users/chrisvernon/Documents/Dev/blendercam/scripts/addons/cam/__init__.py", line 38, in <module>
    from cam import ui, ops, curvecamtools, curvecamequation, curvecamcreate, utils, simple, \
  File "/Users/chrisvernon/Documents/Dev/blendercam/scripts/addons/cam/ui.py", line 33, in <module>
    from cam import gcodeimportparser, simple
  File "/Users/chrisvernon/Documents/Dev/blendercam/scripts/addons/cam/simple.py", line 31, in <module>
    from shapely.geometry import Point, LineString, Polygon, MultiLineString
ModuleNotFoundError: No module named 'shapely'

I'm not familiar shapely, does anyone have any suggestions?

thanks in advance
